export default {
  /* user */
  USER_FETCH_LOGIN: "USER_FETCH_LOGIN",
  USER_FETCH_LOGIN_SUCCESS: "USER_FETCH_LOGIN_SUCCESS",
  USER_FETCH_TRY_AUTO_LOGIN: "USER_FETCH_TRY_AUTO_LOGIN",
  USER_LOGOUT: "USER_LOGOUT",
  USER_FETCH_CLICK_LOG: "USER_FETCH_CLICK_LOG",

  /* news */
  NEWS_FETCH: "NEWS_FETCH",
  NEWS_FETCH_SUCCESS: "NEWS_FETCH_SUCCESS",

  /* search */
  SEARCH_FETCH: "SEARCH_FETCH",
  SEARCH_FETCH_SUCCESS: "SEARCH_FETCH_SUCCESS",

  /* error */
  ERROR_USER: "ERROR_USER",
  ERROR_SEARCH: "ERROR_SEARCH",
  ERROR_NEWS: "ERROR_NEWS"
};
