export default {
  /* auth */
  USER_FETCH_LOGIN: "USER_FETCH_LOGIN",
  USER_FETCH_TRY_AUTO_LOGIN: "USER_FETCH_TRY_AUTO_LOGIN",
  USER_LOGOUT: "USER_LOGOUT",
  USER_ERROR: "USER_ERROR",

  /* news */
  NEWS_FETCH: "NEWS_FETCH",
  NEWS_ERROR: "NEWS_ERROR"
};
