export default {
  /* auth */
  LOGIN_USER: "LOGIN_USER",
  LOGOUT_USER: "LOGOUT_USER",
  AUTO_LOGIN: "AUTO_LOGIN",
  AUTH_ERROR: "AUTH_ERROR",

  /* news */
  FETCH_NEWS: "FETCH_NEWS",
  FETCH_NEWS_ERROR: "FETCH_NEWS_ERROR",

  /* testing */
  FETCH_TEXT: "FETCH_TEXT"
};
